### ISSUE TITLE
Style doesn't install says "Failed to install userstyle" (without exact error)

### ISSUE THREAD

**Issue by msva** [StylishThemes/StackOverflow-Dark#177]
* **Browser**: Chrome 77.0.3865.10
* **Operating System**: Gentoo GNU/Linux
* **Link to page with the issue**: https://raw.githubusercontent.com/StylishThemes/StackOverflow-Dark/master/stackoverflow-dark.user.css
* **Screenshots**:
![image](https://user-images.githubusercontent.com/268102/62612524-bb64eb00-b931-11e9-9e63-a0141cd08a7d.png)
![image](https://user-images.githubusercontent.com/268102/62612603-e3544e80-b931-11e9-9e26-3fd28c0a1a7f.png)

----

Hi there! I found the strange issue: When I clicking on "Install/Reinstall style" button in Stylus, I'm getting a strange error (see the screenshots). It looks like it should also add exact error text at the end of displayed text, but it does not...

I guess, the real issue is the size of the style, since when I created a new style, copy-pasted the code there and tried to bisect the block which produces the fail, it helped to just drop 10-20 `@-moz` blocks. Then style saved just fine. And even returning of one few-lines-long block prevents it from saving.

Can you advice me, is it any way to fix/workaround that problem?
// P.S. GithubDark style doesn't fail on that and install just fine...

**Comment by msva** [comment]
Well, the fact that GH-Dark script installs fine makes the thing much more stranger:
```ShellSession
$  curl https://raw.githubusercontent.com/StylishThemes/StackOverflow-Dark/master/stackoverflow-dark.user.css -s | wc -c
156712
$  curl https://raw.githubusercontent.com/StylishThemes/GitHub-Dark/master/github-dark.user.css -s | wc -c
644859
```

**Comment by Mottie** [comment]
Hi @msva!

This should be fixed in [Stylus' current master branch](https://github.com/openstyles/stylus). Please test this by [side-loading Stylus](https://github.com/openstyles/stylus/wiki/Install-Stylus-from-GitHub) and installing that script.

Don't forget to backup your current styles before messing around with the extension.

**Comment by msva** [comment]
@Mottie Yup, it works fine on Stylus from master (but since it wouldn't receive updates, IIRC, I'd "downgrade" back to 1.5.4 for now)...
Is it any news about the date of new release of Stylus?

**Comment by Mottie** [comment]
> Is it any news about the date of new release of Stylus?

I was going to do it yesterday, but had other things come up. I'll get to it later today.

**Comment by msva** [comment]
Thanks!

**Comment by msva** [comment]
Well, it is pretty strange, but nope, upgrading to the 1.5.5 doesn't fix the issue (despite the fact it exported fine on master before tagging 1.5.5)...
Although, something was definitely fixed, since it started to save the parameters (that was additional issue)...
But neither re-installing the style, nor installing from scratch works for me :-/

**Comment by msva** [comment]
Well... I tried to remove the github dark style, and then SO style installed just fine.
But now GH Dark refuses to install :cry:

**Comment by Mottie** [comment]
Hmm, please [open an issue in the Stylus repo](https://github.com/openstyles/stylus/issues) describing this issue. And please check the console and report any errors.
